wordpressUsername: user

wordpressPassword: ""

wordpressEmail: mazurov1804@gmail.com

wordpressBlogName: YMazurov

wordpressFirstName: Yuheni  
wordpressLastName: Mazurau

replicaCount: 2

ingress:

  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/server-alias: "wordpress.k8s-8.sa"
  hosts:
    - host: wordpress.k8s-8.sa
      paths:
        - path: /
          pathType: ImplementationSpecific


mariadb:
  enabled: false
  replication:
    enabled: false

externalDatabase:
  host: 192.168.202.20
  user: ym_wordpress
  password: "ym_wordpress"
  database: bn_wordpress
  port: 3306 